-- Critica adicionada em MACV_CONSISTELOTECOMPRA

-- Giuliano 12/06/26
-- Trava Fornec+Representante com Acordos/Parcelas vencidas e não quitadas

SELECT DISTINCT X.SEQGERCOMPRA,
                110 CODIGOCONSIST,
               'Existem Pagamentos/Parcelas de Acordos Vencidas e não Quitadas para o Representante!' DESCRICAO,
               'Rep.: '||F.Nomerazao||' Acordo: '||FI.NROTITULO||' Parcela: '||FI.NROPARCELA||'/'||FI.QTDPARCELA||' Valor.: '||TO_CHAR(FI.VLRORIGINAL - FI.VLRPAGO) COMPLEMENTO,
               'B' BLOQUEIOLIBERACAO
  FROM MAC_GERCOMPRA X INNER JOIN esp_Mac_GerCompraCompl C ON X.SEQGERCOMPRA = C.SEQGERCOMPRA
                       INNER JOIN MAF_FORNECCONTATO F ON F.SEQFORNECCONTATO = C.SEQFORNECCONTATO
                       INNER JOIN MAC_GERCOMPRAFORN FO ON FO.SEQGERCOMPRA = X.SEQGERCOMPRA
                       INNER JOIN FI_TITULO FI ON FI.SEQPESSOA = FO.SEQFORNECEDOR AND FI.CODESPECIE LIKE 'AC%' AND FI.ABERTOQUITADO = 'A'
                       
WHERE X.TIPOLOTE = 'C' 
  AND X.SITUACAOLOTE NOT IN ('F','C')
  AND X.DTAHORINCLUSAO >= SYSDATE - 30
  AND EXISTS (SELECT 1 FROM NAGT_LOG_ENVIO_ACO_EMAIL AC WHERE AC.NRO_ACORDO = FI.NROTITULO AND AC.PARCELA = FI.NROPARCELA||'/'||FI.QTDPARCELA AND AC.DATA_ENVIO >= DATE '2026-08-01' AND AC.TIPO = 'Regua' HAVING COUNT(1) = 4)
  AND NOT EXISTS (SELECT 1 FROM NAGT_LOTE_LIBERADO_CRIT L WHERE L.SEQGERCOMPRA = X.SEQGERCOMPRA)
