CREATE OR REPLACE VIEW NAGV_BASE_REGUA_COBRANCA AS
SELECT Initcap(X.DESCACORDO) DESCACORDO, X.NRO_ACORDO, F.DTAVENCIMENTO, F.NROPARCELA||'/'||F.QTDPARCELA PARCELA,
       'R$ '||TO_CHAR(X.VLR_ACORDO, 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR_ACO,
       'R$ '||TO_CHAR(F.VLRORIGINAL - F.VLRPAGO, 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR_PARC_ABERTO,
       F.DTAVENCIMENTO - TRUNC(SYSDATE) DIAS_ATE_VENC,
       X.EMAIL EMAIL_REP, X.TIPO_ACORDO, X.COD_FORNECEDOR, X.COMPRADOR,
       INITCAP(X.RESPACORDONOME) NOME_REPRES, fEmailFinFornec(X.COD_FORNECEDOR) EMAIL_FIN_FORNEC, X.COD_COMPRADOR, X.FORNECEDOR,
       --Criando indexes para regra na regua de cobranca
       CASE WHEN F.DTAVENCIMENTO - TRUNC(SYSDATE) = -1 THEN 1
            WHEN F.DTAVENCIMENTO - TRUNC(SYSDATE) = -6 THEN 2
            WHEN F.DTAVENCIMENTO - TRUNC(SYSDATE) = -11  THEN 3
            WHEN F.DTAVENCIMENTO - TRUNC(SYSDATE) <= -16 THEN 4 END NIVEL_REGUA
       --
  FROM NAGV_TAE_ACORDOS_V4 X INNER JOIN FI_TITULO F ON F.NROTITULO = X.NRO_ACORDO AND F.NROEMPRESA = NVL(X.NROEMPRACORDOPROMOC,X.NRO_EMPRESA) AND F.SITUACAO != 'C' AND F.SEQPESSOA = X.COD_FORNECEDOR
 WHERE F.ABERTOQUITADO = 'A'
   AND X.STATUS = 'Envelope finalizado'
   AND X.DATA_EMISSAO >= DATE '2026-07-14'
   AND
    CASE WHEN F.DTAVENCIMENTO - TRUNC(SYSDATE) = -1 THEN 1
            WHEN F.DTAVENCIMENTO - TRUNC(SYSDATE) = -6 THEN 2
            WHEN F.DTAVENCIMENTO - TRUNC(SYSDATE) = -11  THEN 3
            WHEN F.DTAVENCIMENTO - TRUNC(SYSDATE) <= -16 THEN 4 END

            IS NOT NULL
   AND NOT EXISTS -- evita duplicidade de envio no dia
       (SELECT 1 FROM NAGT_LOG_ENVIO_ACO_EMAIL XX WHERE XX.NRO_ACORDO = X.NRO_ACORDO AND XX.DATA_ENVIO >= TRUNC(SYSDATE) AND XX.TIPO = 'Regua')
;
