CREATE OR REPLACE VIEW NAGV_BASE_REGUA_COBRANCA_ELEGIVEIS AS
SELECT "NIVEL_REGUA","NRO_ACORDO","DTAVENCIMENTO","PARCELA","EMAIL_REP","EMAIL_FIN_FORNEC","COD_COMPRADOR","FORNECEDOR","COD_FORNECEDOR" FROM (
SELECT --Criando indexes para regra na regua de cobranca
       CASE WHEN NOT EXISTS ( (SELECT 1 FROM NAGT_LOG_ENVIO_ACO_EMAIL XXX WHERE XXX.NRO_ACORDO = BS.NRO_ACORDO AND XXX.EMAIL_DESTINO LIKE '%'||EMAIL_REP||'%' AND TIPO = 'Elegiveis') ) THEN 1
         ELSE (SELECT CASE WHEN TRUNC(MIN(XXX.DATA_ENVIO)) - TRUNC(SYSDATE) = -6 THEN 2
                           WHEN TRUNC(MIN(XXX.DATA_ENVIO)) - TRUNC(SYSDATE) = -11  THEN 3
                           WHEN TRUNC(MIN(XXX.DATA_ENVIO)) - TRUNC(SYSDATE) <= -16 THEN 4 END
                 FROM NAGT_LOG_ENVIO_ACO_EMAIL XXX WHERE XXX.NRO_ACORDO = BS.NRO_ACORDO AND XXX.EMAIL_DESTINO LIKE '%'||EMAIL_REP||'%' AND TIPO = 'Elegiveis') END NIVEL_REGUA, BS.*
  FROM (
SELECT F.NROTITULO NRO_ACORDO, F.DTAVENCIMENTO, F.NROPARCELA||'/'||F.QTDPARCELA PARCELA,
       (SELECT LISTAGG(DISTINCT CO.EMAILACORDO, ';') WITHIN GROUP (ORDER BY SEQFORNECEDOR) FROM MAF_FORNECCONTATO CO WHERE CO.SEQFORNECEDOR = F.SEQPESSOA) EMAIL_REP,
       fEmailFinFornec(F.SEQPESSOA) EMAIL_FIN_FORNEC,
       (SELECT MAX(SEQCOMPRADOR) FROM MSU_ACORDOPROMOC C WHERE C.NROACORDO = F.NROTITULO) COD_COMPRADOR, G.NOMERAZAO FORNECEDOR, F.SEQPESSOA COD_FORNECEDOR
       --
  FROM FI_TITULO F INNER JOIN GE_REDEPESSOA GR ON GR.SEQPESSOA = F.SEQPESSOA
                   INNER JOIN NAGT_DEPARA_ELEGIVEIS_030926 D ON D.SEQREDE = GR.SEQREDE
                   INNER JOIN GE_PESSOA G ON G.SEQPESSOA = F.SEQPESSOA

 WHERE F.ABERTOQUITADO = 'A'
   AND F.SITUACAO != 'C'
   AND F.DTAINCLUSAO < DATE '2026-08-03'
   AND F.CODESPECIE LIKE 'AC%'
   AND
    CASE WHEN F.DTAVENCIMENTO - TRUNC(SYSDATE) = -1 THEN 1
            WHEN F.DTAVENCIMENTO - TRUNC(SYSDATE) = -6 THEN 2
            WHEN F.DTAVENCIMENTO - TRUNC(SYSDATE) = -11  THEN 3
            WHEN F.DTAVENCIMENTO - TRUNC(SYSDATE) <= -16 THEN 4 END

            IS NOT NULL
   AND NOT EXISTS -- evita duplicidade de envio na outra regua
       (SELECT 1 FROM NAGT_LOG_ENVIO_ACO_EMAIL XX WHERE XX.NRO_ACORDO = F.NROTITULO AND XX.TIPO = 'Regua')
   AND NOT EXISTS -- evita duplicidade de envio no dia
       (SELECT 1 FROM NAGT_LOG_ENVIO_ACO_EMAIL XX WHERE XX.NRO_ACORDO = F.NROTITULO AND XX.DATA_ENVIO >= TRUNC(SYSDATE) AND XX.TIPO = 'Elegiveis')) BS
WHERE EMAIL_REP IS NOT NULL)

WHERE NIVEL_REGUA IS NOT NULL
;
